# Test
name: CI on develop
on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven in batch mode
      run: ./mvnw -B compile test --file pom.xml
    - name: Sonar quality
      run: ./mvnw -B -P sonar -Dsonar.login=$SONAR_TOKEN --file pom.xml clean verify sonar:sonar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}      
    - name: Build failed Notification
      if: failure()
      uses: rtCamp/action-slack-notify@v2.1.0
      env:
        SLACK_TITLE: ERROR Github Msg
        SLACK_COLOR: '#ee0000'
        SLACK_CHANNEL: fr-timekeeper
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }} 
