name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: 'Greets Action'
        # You may pin to the exact commit or the version.
        # uses: Manoj-Paramsetti/greets-action@514a98c34c34c585c1316371757698ac6af7df48
        uses: Manoj-Paramsetti/greets-action@1.0
        with:
          # Github token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # issue message to be posted
          issue_message: 'Tu as créé une issue'
          # label to be added
          label_1: world
          # PR message to be posted
          pr_message: 'Tu as créé une pull request'
