name: Greetings

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: 'Greets Action'
        uses: Manoj-Paramsetti/greets-action@1.0
        with:
          # Github token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # issue message to be posted
          issue_message: 'Tu as créé une issue'
          # label to be added
          label_1: 'hello world'
