# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on: 
  push :
    branches:
      - 'main'

jobs:

  test:
      name: Test - Units & Integrations
      runs-on: ubuntu-18.04

      steps:
        - uses: actions/checkout@v1
        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 11.0.4
        - name: Maven Package
          run: mvn -B clean package -DskipTests
        - name: Maven Verify
          run: mvn -B clean verify -Pintegration-test

#  release:
#        runs-on: ubuntu-latest
#        steps:
#          - uses: actions/checkout@v2
#
#          - name: Set up JDK 16
#            uses: actions/setup-java@v2
#            with:
#              java-version: '16'
#
#          - name: Release
#            run: mvn -B release:prepare release:perform
#            
          # Création d'une Release Github
#          - name: Publish Github Release
#            uses: softprops/action-gh-release@v1
#            with:
#              tag_name: ${{ steps.tag-name.outputs.TAG }} # On récupère le tag extrait au step précédent.
#              files: target/*.jar # Attachement du jar produit à la release Github
#
